RestaurantApp/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from restaurants import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.HomeView.as_view(), name='home'),

    path('restaurants/', views.RestaurantListView.as_view(), name='restaurant-list'),
    path('restaurants/<int:pk>/', views.RestaurantDetailView.as_view(), name='restaurant-detail'),
    
    path('restaurants/<int:restaurant_id>/review/', views.ReviewCreateView.as_view(), name='add-review'),
    path('restaurant/<int:restaurant_id>/review/<int:pk>/edit', views.ReviewEditView.as_view(), name='edit-review'),
    path('restaurant/<int:restaurant_id>/review/<int:pk>/delete', views.ReviewDeleteView.as_view(), name='delete-review'),

    path('restaurant/<int:restaurant_id>/dish/add/', views.DishCreateView.as_view(), name='dish-add'),
    path('restaurant/<int:restaurant_id>/dish/<int:pk>/edit/', views.DishUpdateView.as_view(), name='dish-edit'),
    path('restaurant/<int:restaurant_id>/dish/<int:pk>/delete/', views.DishDeleteView.as_view(), name='dish-delete'),

    path('restaurants/<int:restaurant_id>/bookmark/', views.bookmark_restaurant, name='bookmark-restaurant'),
    path('bookmarked-restaurants/', views.bookmarked_restaurants, name='bookmarked-restaurants'),
    path('rm-bookmark/<int:bookmark_id>/', views.remove_bookmark, name='remove-bookmark'),

    path('restaurant/<int:restaurant_id>/visit/', views.visit_restaurant, name='visit-restaurant'),
    path('visited-restaurants/', views.visited_restaurants, name='visited-restaurants'),
    path('rm-visit/<int:visit_id>/', views.remove_visit, name='remove-visit'),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.


class Restaurant(models.Model):

    DIETARY_CHOICES = [
        ('veg' , 'Vegetarian'),
        ('vegan', 'Vegan'),
        ('non-veg', 'Non vegetarian'),
        
    ]

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    cost_for_two = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.DecimalField(max_digits=2, decimal_places=1)
    location = models.CharField(max_length=255)
    address= models.TextField()
    timings = models.CharField(max_length=20)
    dietary_preference = models.CharField(max_length=20, choices=DIETARY_CHOICES)
    spotlight = models.BooleanField(default=False)


    def __str__(self):
        return self.title
    
    def update_rating(self):
        avg_rating = self.reviews.aggregate(Avg('rating'))['rating__avg']

        if avg_rating is not None:
            self.rating = round(avg_rating, 1)
        else:
            self.rating=0.0
        self.save()

        
class RestaurantPhoto(models.Model):
    restaurant = models.ForeignKey(Restaurant, related_name='photos', on_delete=models.CASCADE)
    image=models.ImageField(upload_to = 'restaurant_photos/')
    uploaded_at = models.DateTimeField(auto_now_add = True)
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f'Photo of {self.restaurant.title}'
    
    
class Dish(models.Model):

    CUISINE_CHOICES = [
        ('NI', 'North Indian'),
        ('SI', 'South Indian'),
        ('EI', 'East Indian'),
        ('IF', 'Indian Fusion'),
    ]

    name = models.CharField(max_length=255)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='menu_items')
    price = models.DecimalField(max_digits=5, decimal_places=2)
    is_veg = models.BooleanField(default=False)
    image = models.ImageField(upload_to='dish_photos/', null=True, blank=True)
    is_deleted= models.BooleanField(default=False)
    cuisine_type = models.CharField(max_length=20, choices=CUISINE_CHOICES)

    def __str__(self):
        return f'{self.name} of {self.restaurant.title}'
    

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, related_name='reviews', on_delete=models.CASCADE)
    rating = models.FloatField(
        validators=[
            MinValueValidator(1.0),
            MaxValueValidator(5.0)
        ],
        help_text="Rating must be between 1.0 and 5.0."
    )
    comment = models.TextField()

    def __str__(self):
        return f'{self.user.username} gave {self.rating} to {self.restaurant}'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.restaurant.update_rating()


class VisitedRestaurant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, related_name='visits', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} - {self.restaurant.title}'
    

class BookmarkedRestaurant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, related_name='bookmarks' ,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} - {self.restaurant.title}'

restaurants/forms.py
from django import forms
from .models import Review
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        

class ReviewForm(forms.ModelForm):
    RATING_CHOICES = [
        (1.0, '1.0'),
        (1.5, '1.5'),
        (2.0, '2.0'),
        (2.5, '2.5'),
        (3.0, '3.0'),
        (3.5, '3.5'),
        (4.0, '4.0'),
        (4.5, '4.5'),
        (5.0, '5.0'),
    ]

    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.Select)

    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 4}),
        }

restaurants/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from django.views.generic import TemplateView, ListView, DetailView
from .models import Restaurant, RestaurantPhoto, Dish, Review, BookmarkedRestaurant, VisitedRestaurant

from django.core.paginator import Paginator

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ReviewForm, SignUpForm

from django.contrib.auth.decorators import login_required

from .filters import RestaurantFilter, DishFilter

from django.utils.decorators import method_decorator
from .decorators import restaurant_owner_required 
from django.contrib import messages
# Create your views here.


class HomeView(TemplateView):
    template_name ='home.html'


class RestaurantListView(ListView):
    model = Restaurant
    template_name = 'restaurants/list.html'
    context_object_name = 'restaurants'
    paginate_by = 10
    filterset_class = RestaurantFilter

    def get_queryset(self):
        queryset = super().get_queryset().order_by('id')
        self.filterset = RestaurantFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        if self.request.user.is_authenticated:
            context['bookmarked_restaurants'] = BookmarkedRestaurant.objects.filter(user=self.request.user).values_list('restaurant_id', flat=True)
            context['visited_restaurants'] = VisitedRestaurant.objects.filter(user=self.request.user).values_list('restaurant_id', flat=True)
        else:
            context['bookmarked_restaurants'] = []
            context['visited_restaurants'] = []
        return context
    

class RestaurantDetailView(DetailView):
    model = Restaurant
    template_name = 'restaurants/detail.html'
    context_object_name = 'restaurant'
    filterset_class = DishFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        restaurant = self.object
        context['is_owner'] = restaurant.owner == self.request.user
        menu_items = restaurant.menu_items.filter(is_deleted=False)
        self.filterset = self.filterset_class(self.request.GET, queryset=menu_items)
        context['menu_items'] = self.filterset.qs
        context['filter'] = self.filterset
        context['reviews'] = restaurant.reviews.order_by('-id')
        context['existing_review'] = Review.objects.filter(user=self.request.user, restaurant=self.object).first()
        return context


class DishCreateView(CreateView):
    model = Dish
    fields = ['name', 'price', 'is_veg', 'image', 'cuisine_type']
    template_name = 'restaurants/dish_form.html'

    @method_decorator(restaurant_owner_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Add'
        return context

    def form_valid(self, form):
        restaurant = get_object_or_404(Restaurant, pk=self.kwargs['restaurant_id'])
        form.instance.restaurant = restaurant
        return super().form_valid(form)
        
    def get_success_url(self):
        return reverse_lazy('restaurant-detail', kwargs={'pk': self.object.restaurant.pk})


class DishUpdateView(UpdateView):
    model = Dish
    fields = ['name', 'price', 'is_veg', 'image', 'cuisine_type']
    template_name = 'restaurants/dish_form.html'

    @method_decorator(restaurant_owner_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Edit'
        return context

    def get_queryset(self):
        restaurant = get_object_or_404(Restaurant, pk=self.kwargs['restaurant_id'])
        return restaurant.menu_items.all()
    
    def get_success_url(self):
        return reverse_lazy('restaurant-detail', kwargs={'pk': self.object.restaurant.pk})


class DishDeleteView(DeleteView):
    model = Dish
    template_name = 'restaurants/dish_confirm_delete.html'

    @method_decorator(restaurant_owner_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        restaurant = get_object_or_404(Restaurant, pk=self.kwargs['restaurant_id'])
        return restaurant.menu_items.all()
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_deleted = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('restaurant-detail', kwargs={'pk': self.object.restaurant.pk})
 

class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'restaurants/review_form.html'

    def dispatch(self, request, *args, **kwargs):
        self.restaurant = get_object_or_404(Restaurant, pk=self.kwargs['restaurant_id'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form): 
        existing_review = Review.objects.filter(user=self.request.user, restaurant=self.restaurant).first()
        if existing_review:
            messages.warning(self.request, "You have already reviewed this restaurant.")
            return redirect('restaurant-detail', pk=self.restaurant.pk)
    
        form.instance.user = self.request.user
        form.instance.restaurant = self.restaurant
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['restaurant'] = get_object_or_404(Restaurant, pk=self.kwargs['restaurant_id'])
        return context

    def get_success_url(self):
        return reverse('restaurant-detail', kwargs={'pk': self.object.restaurant.pk})
    

class ReviewEditView(LoginRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = 'restaurants/review_form.html'

    def get_object(self, queryset=None):
        review = super().get_object(queryset)
        self.restaurant = review.restaurant  
        return review

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['restaurant'] = self.restaurant
        return context
    
    def get_success_url(self):
        return reverse_lazy('restaurant-detail', kwargs={'pk': self.object.restaurant.pk})

    def get_queryset(self):
        return Review.objects.filter(user=self.request.user)

class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    model = Review
    template_name = 'restaurants/review_confirm_delete.html'

    def get_success_url(self):
        messages.success(self.request, "Your review has been deleted successfully.")
        return reverse_lazy('restaurant-detail', kwargs={'pk': self.object.restaurant.pk})

    def get_queryset(self):
        return Review.objects.filter(user=self.request.user)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

@login_required
def bookmark_restaurant(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, id=restaurant_id)
    BookmarkedRestaurant.objects.get_or_create(user=request.user, restaurant=restaurant)
    return redirect('restaurant-list'   )

@login_required
def bookmarked_restaurants(request):
    bookmarks = BookmarkedRestaurant.objects.filter(user=request.user)
    return render(request, 'restaurants/bookmarked.html', {'bookmarks': bookmarks})

@login_required
def remove_bookmark(request, bookmark_id):
    bookmark = get_object_or_404(BookmarkedRestaurant, id=bookmark_id, user=request.user)
    bookmark.delete()
    return redirect('bookmarked-restaurants')

@login_required
def visit_restaurant(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, id=restaurant_id)
    VisitedRestaurant.objects.get_or_create(user=request.user, restaurant=restaurant)
    return redirect('restaurant-list')

@login_required
def visited_restaurants(request):
    visits = VisitedRestaurant.objects.filter(user=request.user)
    return render(request, 'restaurants/visited.html', {'visits': visits})

@login_required
def remove_visit(request, visit_id):
    visit = get_object_or_404(VisitedRestaurant, id=visit_id, user=request.user)
    visit.delete()
    return redirect('visited-restaurants')

templates/restaurants/bookmarked.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2>Your Bookmarked Restaurants</h2>
        {% for bookmark in bookmarks %}
            <div class="restaurant-list">
                <a href="{% url 'restaurant-detail' bookmark.restaurant.id %}">
                    {% if bookmark.restaurant.photos.first %}
                        <img src="{{ bookmark.restaurant.photos.first.image.url }}" alt="{{ bookmark.restaurant.title }} photo">
                    {% else %}
                        <img src="{% static 'img/default_restaurant.jpg' %}" alt="{{ bookmark.restaurant.title }} photo">
                    {% endif %}
                    <div class='res-attributes'>
                        <h3>{{ bookmark.restaurant.title }}</h3>
                        <p>Rating: <b>{{ bookmark.restaurant.rating }}</b></p>
                        <p>Cost for Two:<b> Rs. {{ bookmark.restaurant.cost_for_two }}</b></p>
                        <p>Location: {{ bookmark.restaurant.location }}</p>
                        <p>{{ bookmark.restaurant.address }}</p>
                    </div>
                </a>
                <form action="{% url 'remove-bookmark' bookmark.id %}" method="post" class="bookmark-form">
                    {% csrf_token %}
                    <button type="submit" class="bookmark-btn">
                        <i class="fas fa-trash" style="color:red;"></i>  Remove
                    </button>
                </form>
            </div>
        {% empty %}
            <p>You have no bookmarked restaurants.</p>
            <div class="back-to-list">
                <a href="{% url 'restaurant-list' %}"> Add Bookmarks </a>
            </div>
        {% endfor %}
{% endblock %}

templates/restaurants/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div id="filter-section">
    <form method="get"> 
        {{ filter.form.dish_search}}
        <button type="submit"><i class="fas fa-search"></i></button><br>
        <select name="cuisine_type" onchange="this.form.submit()">
            {% for choice in filter.form.cuisine_type.field.choices %}
                <option value="{{ choice.0 }}" {% if filter.form.cuisine_type.value == choice.0 %}selected{% endif %}>
                    {{ choice.1 }}
                </option>
            {% endfor %}
        </select>

        <select name="price_order" id="price_order" onchange="this.form.submit()">
            <option value="">Sort by Cost</option>
            <option value="price" {% if request.GET.price_order == "price" %}selected{% endif %}>Cost:Low to High</option>
            <option value="-price" {% if request.GET.price_order == "-price" %}selected{% endif %}>Cost:High to Low</option>
        </select>
        
        <div class="toggle-container">
            <span>Veg</span>
            <label class="switch">
                <input type="checkbox" name="is_veg" 
                   value="1" 
                   {% if request.GET.is_veg %}checked{% endif %}
                   onchange="this.form.submit();"> 
                <span class="slider round"></span>
            </label>
        </div>
    </form>
</div>

    <h2>Menu for {{ restaurant.title }}</h2>
    {% if is_owner %}
        <a href="{% url 'dish-add' restaurant.id %}" class="btn btn-add">
                    <i class="fas fa-plus"> </i> Add New Dish
        </a>
    {% endif %}
    {% for dish in menu_items %}
        <div class=restaurant-list>
            {% if dish.image %}
                <img src="{{ dish.image.url }}" alt="{{ restaurant.title }} photo">
            {% else %}
                <img src="{% static 'img/default_dish.jpg' %}" alt="{{ restaurant.title }} photo">
            {% endif %}
            
            <div class='res-attributes'>
                <h3>{{ dish.name }}</h3>
                <p> <b>Rs.{{ dish.price }}</b></p>
                <p>{{ dish.get_cuisine_type_display }}</p>
                <div class=foodtype>
                    {% if dish.is_veg %}
                        <img src="{% static 'img/veg.png' %}" alt="Vegetarian" title="Vegetarian">
                    {% else %}
                        <img src="{% static 'img/nonveg.png' %}" alt="Non-Vegetarian" title="Non-Vegetarian">
                    {% endif %}
                </div>
                {% if is_owner %}
                    <a href="{% url 'dish-edit' restaurant.id dish.id %}" class="btn btn-edit">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a href="{% url 'dish-delete' restaurant.id dish.id %}" class="btn btn-delete">
                        <i class="fas fa-trash"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    {% empty %}
        <p>No dishes available at the moment.</p>
    {% endfor %}

    <div class="reviews">
        {% if existing_review %}
            <a href="{% url 'edit-review' restaurant_id=restaurant.pk pk=existing_review.pk %}">Edit</a>
            <a href="{% url 'delete-review' restaurant_id=restaurant.pk pk=existing_review.pk %}">Delete</a>
        {% else %}
            <a href="{% url 'add-review' restaurant.id %}">Add Review</a>
        {% endif %}

        {% if messages %}
            <p class="messages">
                {% for message in messages %}
                    <p class="{% if message.tags %}{{ message.tags }}{% endif %}" style="color:red;">
                        {{ message }}
                    <p>
                {% endfor %}
            <p>
        {% endif %}
        <h2>Reviews</h2>
        <ul>
            {% for review in reviews %}
                <div class="review-list">
                    <li>
                        <strong>{{ review.user.username }}</strong>
                        <p><b>{{ review.rating }}</b></p>
                        <span class="star-rating">
                                {% for i in "12345" %}
                                    {% with rating_value=review.rating %}
                                        {% if rating_value >= forloop.counter %}
                                            <i class="fas fa-star"></i>
                                        {% elif rating_value > forloop.counter|add:-1 and rating_value < forloop.counter|add:0 %}  <!-- Check for half star -->
                                            <i class="fas fa-star-half-alt"></i>
                                        {% else %}
                                            <i class="far fa-star"></i>
                                        {% endif %}
                                    {% endwith %}
                                {% endfor %}
                        </span>
                        <p>{{ review.comment }}</p>
                    </li>
                    {% if review.user == request.user %}
                    <div class="review-actions">
                        <a href="{% url 'edit-review' restaurant.id review.id %}" class="btn btn-edit">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a href="{% url 'delete-review' restaurant.id review.id %}" class="btn btn-delete">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                    {% endif %}
                </div>
            {% empty %}
                <p>No reviews yet.</p>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/restaurants/dish_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="confirmation-dialog">
    <h2>Are you sure you want to mark {{ dish.name }} as deleted?</h2>
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Confirm</button>
        <a href="{% url 'restaurant-detail' dish.restaurant.id %}">Cancel</a>
    </form>
</div>

{% endblock %}

templates/restaurants/dish_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class='dish-form'>
    <h2>{{ action }} Dish</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-field">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name }}
        </div>
        <div class="form-field">
            <label for="{{ form.price.id_for_label }}">{{ form.price.label }}</label>
            {{ form.price }}
        </div>
        <div class="form-field">
            <label for="{{ form.is_veg.id_for_label }}">{{ form.is_veg.label }}</label>
            {{ form.is_veg }}
        </div>
        <div class="form-field">
            <label for="{{ form.image.id_for_label }}">{{ form.image.label }}</label>
            {{ form.image }}
        </div>
        <div class="form-field">
            <label for="{{ form.cuisine_type.id_for_label }}">{{ form.cuisine_type.label }}</label>
            {{ form.cuisine_type }}
        </div>
        <button type="submit">{{ action }}</button>
    </form>
</div>


{% endblock %}

templates/restaurants/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Available Restaurants{% endblock %}

{% block content %}

<div id="filter-section">
    
        <form method="get">
            {{ filter.form.search }}
            <button type="submit"><i class="fas fa-search"></i></button><br>
            
            <select name="dietary_preference" onchange="this.form.submit()">
                {% for choice in filter.form.dietary_preference.field.choices %}
                    <option value="{{ choice.0 }}" {% if filter.form.dietary_preference.value == choice.0 %}selected{% endif %}>
                        {{ choice.1 }}
                    </option>
                {% endfor %}
            </select>
            
            <select name="cost_order" id="cost_order" onchange="this.form.submit()">
                <option value="">Sort by Cost</option>
                <option value="cost_for_two" {% if request.GET.cost_order == "cost_for_two" %}selected{% endif %}>Cost:Low to High</option>
                <option value="-cost_for_two" {% if request.GET.cost_order == "-cost_for_two" %}selected{% endif %}>Cost:High to Low</option>
            </select>

            <select name="rating_order" id="rating_order" onchange="this.form.submit()">
                <option value="">Sort by Rating</option>
                <option value="rating" {% if request.GET.rating_order == "rating" %}selected{% endif %}>Rating:Low to High</option>
                <option value="-rating" {% if request.GET.rating_order == "-rating" %}selected{% endif %}>Rating:High to Low</option>            
            </select>
            <div class="toggle-container">
                <span>Spotlight</span>
                <label class="switch">
                    <input type="checkbox" name="spotlight" 
                       value="1" 
                       {% if request.GET.spotlight %}checked{% endif %}
                       onchange="this.form.submit();"> 
                <span class="slider round"></span>
                </label>

            </div>
        </form>
</div>

<h2>Explore our Restaurants</h2>
<p>Discover a variety of dining options and enjoy a delicious experience!</p>


<div id="all-restaurants">
{% if restaurants %}
    {% for restaurant in restaurants %}
        <div class="restaurant-list">
            <a href="{% url 'restaurant-detail' restaurant.pk %}">
                {% if restaurant.photos.first %}
                    <img src="{{ restaurant.photos.first.image.url }}" alt="{{ restaurant.title }} photo">
                {% else %}
                    <img src="{% static 'img/default_restaurant.jpg' %}" alt="{{ restaurant.title }} photo">
                {% endif %}
                <div class='res-attributes'>
                    <h3>{{ restaurant.title }}</h3>
                    <p>Rating: <b>{{ restaurant.rating }}</b></p>
                    <p>Cost for Two:<b> Rs. {{ restaurant.cost_for_two }}</b></p>
                    <p>Location: {{ restaurant.location }}</p>
                    <p>{{ restaurant.address }}</p>
                </div>
            </a>
            <form action="{% url 'bookmark-restaurant' restaurant.id %}" method="post" class="bookmark-form">
                {% csrf_token %}
                <button type="submit" class="bookmark-btn" 
                        {% if restaurant.id in bookmarked_restaurants %}disabled{% endif %}>
                        <i class="fas fa-bookmark" 
                            {% if restaurant.id in bookmarked_restaurants %}style="color: red;"{% else %}style="color: gray;"{% endif %}>
                        </i>
                </button>
            </form>
            <form action="{% url 'visit-restaurant' restaurant.id %}" method="post" class="visit-form">
    {% csrf_token %}
    <button type="submit" class="visit-btn">
        {% if restaurant.id in visited_restaurants %}
            <i class="fas fa-check" style="color: green;"></i> 
            visited
        {% else %}
            <i class="fas fa-check-circle" style="color: gray;"></i>
            mark as visited
        {% endif %}
    </button>
</form>
        </div>
    {% endfor %}
{% else %}
    <h3>No restaurants available at the moment. Please check back later!</h3>
{% endif %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

templates/restaurants/review_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="confirmation-dialog">

    <h2>Confirm Deletion</h2>
    <p>Are you sure you want to delete this review?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
        <a href="{% url 'restaurant-detail' review.restaurant.id %}">Cancel</a>
    </form>
{% endblock %}

templates/restaurants/review_form.html
{% extends 'base.html' %}
{% block content %}

<div class="review-form-container">
    <h2>Add a Review for {{ restaurant.title }}</h2>
    <form method="post" class="review-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit-btn">Submit Review</button>
    </form>
    <a href="{% url 'restaurant-detail' restaurant.id %}" class="back-link">Back to Restaurant Details</a>    
</div>

{% endblock %}